Repository NullVoxPopuli/ember-apply, pull requests merged in 2025-01, with the labels that each got.

#581 Add tsconfig utilities
  build-docs.sh
  ember-apply/package.json
  ember-apply/src/-private/tsconfig/index.js
  ember-apply/src/-private/tsconfig/types.ts
  ember-apply/src/index.js
  ember-apply/tests/__snapshots__/cli.test.ts.snap
  ember-apply/tests/tsconfig.test.ts
  package.json
  packages/docs/package.json
  packages/ember/embroider/__snapshots__/index.test.ts.snap
  packages/ember/tailwind-webpack/__snapshots__/index.test.ts.snap
  packages/ember/tailwind/__snapshots__/index.test.ts.snap
  packages/ember/typescript/tests/__snapshots__/e2e.test.ts.snap
  pnpm-lock.yaml
Labels: enhancement

#584 npx create-release-plan-setup@latest --update
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#590 feat: Rename tailwind-vite to tailwind3-vite
  README.md
  packages/ember/tailwind3-vite/.eslintignore
  packages/ember/tailwind3-vite/.eslintrc.cjs
  packages/ember/tailwind3-vite/__snapshots__/index.test.ts.snap
  packages/ember/tailwind3-vite/index.js
  packages/ember/tailwind3-vite/index.test.ts
  packages/ember/tailwind3-vite/package.json
  packages/ember/tailwind3-vite/tsconfig.json
  packages/ember/tailwind3-vite/vitest.config.ts
  pnpm-lock.yaml
Labels: breaking

#591 tailwind4-vite
  README.md
  ember-apply/src/test-utils.js
  packages/ember/tailwind4-vite/.eslintignore
  packages/ember/tailwind4-vite/.eslintrc.cjs
  packages/ember/tailwind4-vite/__snapshots__/index.test.ts.snap
  packages/ember/tailwind4-vite/index.js
  packages/ember/tailwind4-vite/index.test.ts
  packages/ember/tailwind4-vite/package.json
  packages/ember/tailwind4-vite/tsconfig.json
  packages/ember/tailwind4-vite/vitest.config.ts
  pnpm-lock.yaml
Labels: enhancement

#592 docs: tailwind3-vite reference
  README.md
Labels: documentation

#594 fix: tailwind3-vite works
  packages/ember/tailwind3-vite/__snapshots__/index.test.ts.snap
  packages/ember/tailwind3-vite/index.js
  packages/ember/tailwind3-vite/index.test.ts
  packages/ember/tailwind3-vite/vitest.config.ts
Labels: bug
